(define (make-account balance password)
  (let ((count 7))
    (define (withdraw amount)
      (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch input-password m)
      (if (eq? input-password password)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request -- MAKE-ACCOUNT"
                           m)))
        (begin (set! count (- count 1))
               (if (= count 0)
                 call-the-cops
                 complain))))
    dispatch))

(define (call-the-cops x) "call-the-cops")
(define (complain x) "Incorrect password")

